"""Soccer evaluator configuration constants."""

# Soccer evaluator feature flag.
SOCCER_EVALUATOR_ENABLED = False

# Scheduling (in simulation frames; 30 fps).
SOCCER_EVALUATOR_INTERVAL_FRAMES = 1

# Participant thresholds.
SOCCER_EVALUATOR_MIN_PLAYERS = 6
SOCCER_EVALUATOR_NUM_PLAYERS = 20

# Match duration (RCSS cycles at 10Hz).
SOCCER_EVALUATOR_DURATION_FRAMES = 120

# Event tracking.
SOCCER_MAX_EVENTS = 10
SOCCER_EVENT_MAX_AGE_FRAMES = 180

# League scheduling defaults.
SOCCER_LEAGUE_MATCH_EVERY_FRAMES = 60
SOCCER_LEAGUE_MATCHES_PER_TICK = 1
SOCCER_LEAGUE_TEAM_SIZE = 0  # 0 = derive from num_players
SOCCER_LEAGUE_COOLDOWN_MATCHES = 2
SOCCER_LEAGUE_ALLOW_REPEAT_WITHIN_MATCH = False
SOCCER_LEAGUE_SELECTION_STRATEGY = "stratified"

# Reward model defaults.
SOCCER_LEAGUE_ENTRY_FEE_ENERGY = 10.0
SOCCER_LEAGUE_REWARD_MODE = "refill_to_max"
SOCCER_LEAGUE_REWARD_MULTIPLIER = 1.5

# Reproduction reward defaults.
SOCCER_LEAGUE_REPRO_REWARD_MODE = "credits"
SOCCER_LEAGUE_REPRO_CREDIT_AWARD = 2.0
SOCCER_LEAGUE_REPRO_CREDIT_REQUIRED = 1.0
SOCCER_LEAGUE_REPRO_CREDIT_INITIAL = 0.0

# Optional seed override (None -> derive from world seed).
SOCCER_LEAGUE_SEED_BASE = None
