/**
 * Shared inline-style objects for the Evolution Benchmark display components
 * (EvolutionBenchmarkDisplay.tsx, EvolutionBenchmarkMetrics.tsx,
 * EvolutionBenchmarkChart.tsx). Extracted from EvolutionBenchmarkDisplay.tsx
 * (god-class ratchet harvest); values are unchanged.
 */

import { colors } from '../styles/theme';

export const evolutionBenchmarkStyles = {
    // container removed - using glass-panel class
    // header removed - integrated into CollapsibleSection title
    // title removed - styled inline
    tabs: {
        display: 'flex',
        gap: '4px',
        marginLeft: 'auto', // Push tabs to the right
    },
    miniTabs: {
        display: 'flex',
        gap: '4px',
        padding: '3px',
        borderRadius: '8px',
        backgroundColor: 'rgba(15,23,42,0.6)',
        border: `1px solid ${colors.border}`,
    },
    miniTab: {
        padding: '4px 10px',
        borderRadius: '6px',
        border: 'none',
        backgroundColor: 'transparent',
        color: colors.textSecondary,
        cursor: 'pointer',
        fontSize: '12px',
        fontWeight: 600,
    },
    activeMiniTab: {
        padding: '4px 10px',
        borderRadius: '6px',
        border: 'none',
        backgroundColor: '#3b82f6',
        color: '#ffffff',
        cursor: 'pointer',
        fontSize: '12px',
        fontWeight: 700,
    },
    chartLegend: {
        display: 'flex',
        justifyContent: 'flex-end',
        gap: '12px',
        flexWrap: 'wrap' as const,
        padding: '4px 2px 0 2px',
        color: colors.textSecondary,
        fontSize: '11px',
    },
    chartLegendItem: {
        display: 'inline-flex',
        alignItems: 'center',
        gap: '8px',
        padding: '3px 8px',
        borderRadius: '999px',
        backgroundColor: 'rgba(15,23,42,0.45)',
        border: `1px solid rgba(148,163,184,0.18)`,
        userSelect: 'none' as const,
    },
    chartLegendSwatch: {
        width: '22px',
        borderTopWidth: '3px',
        borderTopStyle: 'solid',
        borderTopColor: colors.textSecondary,
        borderRadius: '2px',
        display: 'inline-block',
    },
    tab: {
        background: 'transparent',
        border: `1px solid ${colors.border}`,
        color: colors.textSecondary,
        fontSize: '10px',
        padding: '3px 8px',
        borderRadius: '4px',
        cursor: 'pointer',
    },
    activeTab: {
        background: colors.primary,
        border: `1px solid ${colors.primary}`,
        color: '#fff',
        fontSize: '10px',
        padding: '3px 8px',
        borderRadius: '4px',
        cursor: 'pointer',
    },
    pokerScoreContainer: {
        backgroundColor: colors.bgLight,
        borderRadius: '12px',
        padding: '12px',
        display: 'flex',
        flexDirection: 'column' as const,
        alignItems: 'center',
        justifyContent: 'center',
        gap: '2px',
        height: '100%', // Fill height in grid
        boxSizing: 'border-box' as const,
        border: `2px solid rgba(59, 130, 246, 0.3)`,
    },
    pokerScoreHeader: {
        display: 'flex',
        alignItems: 'center',
        gap: '8px',
        marginBottom: '4px',
    },
    tooltipIcon: {
        display: 'inline-flex',
        alignItems: 'center',
        justifyContent: 'center',
        width: '16px',
        height: '16px',
        borderRadius: '50%',
        backgroundColor: 'rgba(148, 163, 184, 0.3)',
        color: colors.textSecondary,
        fontSize: '10px',
        fontWeight: 700,
        cursor: 'help',
        position: 'relative' as const,
    },
    tooltip: {
        position: 'absolute' as const,
        top: '24px',
        left: '50%',
        transform: 'translateX(-50%)',
        backgroundColor: 'rgba(15, 23, 42, 0.95)',
        border: `1px solid ${colors.border}`,
        borderRadius: '8px',
        padding: '12px 14px',
        fontSize: '11px',
        color: colors.text,
        whiteSpace: 'pre-line' as const,
        width: '260px',
        zIndex: 100,
        boxShadow: '0 4px 12px rgba(0,0,0,0.3)',
        lineHeight: 1.5,
    },
    metricCard: {
        backgroundColor: colors.bgLight,
        borderRadius: '8px',
        padding: '8px 6px',
        display: 'flex',
        flexDirection: 'column' as const,
        alignItems: 'center',
        gap: '2px',
    },
    metricLabel: {
        color: colors.textSecondary,
        fontSize: '10px',
        textTransform: 'uppercase' as const,
        textAlign: 'center' as const,
    },
    bestPerformer: {
        display: 'flex',
        alignItems: 'center',
        gap: '8px',
        padding: '6px 12px',
        backgroundColor: colors.bgLight,
        borderRadius: '6px',
        marginBottom: '4px',
    },
    strategyTag: {
        backgroundColor: 'rgba(167, 139, 250, 0.2)',
        color: '#a78bfa',
        fontSize: '10px',
        padding: '2px 8px',
        borderRadius: '4px',
    },
    improvementBanner: {
        backgroundColor: colors.bgLight,
        borderRadius: '6px',
        padding: '6px 12px',
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        flexWrap: 'wrap' as const,
        gap: '8px',
    },
    checkmarks: {
        display: 'flex',
        gap: '12px',
        fontSize: '11px',
    },
    certaintyPanel: {
        backgroundColor: colors.bgLight,
        borderRadius: '8px',
        padding: '8px 12px',
        border: `1px solid ${colors.border}`,
        display: 'flex',
        flexDirection: 'column' as const,
        gap: '8px',
    },
    certaintyHeader: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        gap: '12px',
        flexWrap: 'wrap' as const,
    },
    certaintyTitle: {
        color: colors.text,
        fontSize: '11px',
        fontWeight: 700,
        textTransform: 'uppercase' as const,
        letterSpacing: '0.04em',
    },
    certaintyMeta: {
        color: colors.textSecondary,
        fontSize: '10px',
        fontFamily: 'var(--font-mono)',
    },
    certaintyGrid: {
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))',
        gap: '8px',
    },
    certaintyMetric: {
        minHeight: '52px',
        borderRadius: '6px',
        backgroundColor: 'rgba(15,23,42,0.45)',
        border: `1px solid rgba(148,163,184,0.16)`,
        padding: '8px 10px',
        display: 'flex',
        flexDirection: 'column' as const,
        justifyContent: 'center',
        gap: '3px',
    },
    certaintyLabel: {
        color: colors.textSecondary,
        fontSize: '10px',
        textTransform: 'uppercase' as const,
    },
    certaintyValue: {
        color: colors.text,
        fontSize: '13px',
        fontWeight: 700,
        fontFamily: 'var(--font-mono)',
    },
    certaintySub: {
        color: colors.textSecondary,
        fontSize: '10px',
        fontFamily: 'var(--font-mono)',
    },
    certaintyEmpty: {
        color: colors.textSecondary,
        fontSize: '11px',
        padding: '4px 0',
    },
    baselineGrid: {
        display: 'flex',
        flexDirection: 'column' as const,
        gap: '6px',
    },
    baselineRow: {
        display: 'flex',
        alignItems: 'center',
        gap: '12px',
    },
    baselineName: {
        width: '120px',
        display: 'flex',
        justifyContent: 'space-between',
        fontSize: '11px',
        color: colors.text,
    },
    difficulty: {
        color: '#eab308',
        fontSize: '9px',
    },
    baselineBar: {
        flex: 1,
        height: '16px',
        backgroundColor: colors.bgLight,
        borderRadius: '4px',
        position: 'relative' as const,
        overflow: 'hidden',
    },
    baselineZeroLine: {
        position: 'absolute' as const,
        left: '50%',
        top: 0,
        bottom: 0,
        width: '1px',
        backgroundColor: colors.border,
    },
    baselineValue: {
        width: '50px',
        textAlign: 'right' as const,
        fontSize: '12px',
        fontWeight: 600,
    },
    longitudinalView: {
        display: 'flex',
        flexDirection: 'column' as const,
        gap: '12px',
    },
    trendSummary: {
        display: 'flex',
        gap: '16px',
        fontSize: '11px',
        color: colors.text,
        flexWrap: 'wrap' as const,
    },
    noData: {
        padding: '24px',
        textAlign: 'center' as const,
        color: colors.textSecondary,
        fontSize: '13px',
    },
    footer: {
        marginTop: '8px',
        paddingTop: '8px',
        borderTop: `1px solid ${colors.border}`,
        textAlign: 'center' as const,
    },
} as const;
