import { colors } from '../styles/theme';

export const styles = {
    panel: {
        backgroundColor: 'rgba(15, 23, 42, 0.52)',
        border: `1px solid ${colors.border}`,
        borderRadius: '10px',
        padding: '16px',
        display: 'flex',
        flexDirection: 'column' as const,
        gap: '14px',
        color: colors.text,
    },
    titleContainer: {
        borderBottom: `1px solid rgba(148, 163, 184, 0.1)`,
        paddingBottom: '8px',
    },
    title: {
        color: colors.textSecondary,
        fontWeight: 700,
        fontSize: '11px',
        letterSpacing: '0.08em',
    },
    scoreRow: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        gap: '12px',
        marginTop: '4px',
    },
    scoreLeft: {
        display: 'flex',
        flexDirection: 'column' as const,
        gap: '2px',
    },
    score: {
        color: colors.text,
        fontSize: '32px',
        fontWeight: 800,
        fontFamily: 'var(--font-mono, monospace)',
        lineHeight: 1.1,
    },
    scoreDenom: {
        color: colors.textSecondary,
        fontSize: '16px',
        fontWeight: 400,
    },
    descriptorText: {
        color: colors.textSecondary,
        fontSize: '12px',
    },
    badge: {
        backgroundColor: 'rgba(74, 222, 128, 0.1)',
        border: `1px solid ${colors.success}`,
        borderRadius: '4px',
        color: colors.success,
        fontSize: '11px',
        fontWeight: 800,
        padding: '4px 8px',
        letterSpacing: '0.04em',
    },
    scaleContainer: {
        position: 'relative' as const,
        height: '70px',
        margin: '12px 0',
        display: 'flex',
        flexDirection: 'column' as const,
    },
    scaleLabels: {
        position: 'relative' as const,
        height: '16px',
        width: '100%',
    },
    markerLabel: {
        position: 'absolute' as const,
        transform: 'translateX(-50%)',
        whiteSpace: 'nowrap' as const,
    },
    markerName: {
        fontSize: '10px',
        color: colors.textSecondary,
    },
    trackLineContainer: {
        position: 'relative' as const,
        height: '14px',
        width: '100%',
        marginTop: '8px',
    },
    trackBackground: {
        position: 'absolute' as const,
        left: 0,
        right: 0,
        top: '6px',
        height: '2px',
        backgroundColor: 'rgba(255, 255, 255, 0.15)',
        borderRadius: '1px',
    },
    trackDot: {
        position: 'absolute' as const,
        width: '6px',
        height: '6px',
        borderRadius: '50%',
        backgroundColor: colors.textSecondary,
        top: '4px',
        transform: 'translateX(-50%)',
    },
    trackDotActive: {
        position: 'absolute' as const,
        width: '10px',
        height: '10px',
        borderRadius: '50%',
        backgroundColor: colors.success,
        top: '2px',
        transform: 'translateX(-50%)',
        boxShadow: `0 0 8px ${colors.success}`,
    },
    scaleValues: {
        position: 'relative' as const,
        height: '16px',
        width: '100%',
        marginTop: '6px',
    },
    markerValueLabel: {
        position: 'absolute' as const,
        transform: 'translateX(-50%)',
        whiteSpace: 'nowrap' as const,
    },
    markerValue: {
        fontSize: '11px',
        color: colors.textSecondary,
        fontWeight: 600,
    },
    averagesInfo: {
        backgroundColor: colors.bgLight,
        borderRadius: '6px',
        padding: '10px 12px',
        display: 'flex',
        flexDirection: 'column' as const,
        gap: '4px',
    },
    averagesTitle: {
        color: colors.textSecondary,
        fontSize: '11px',
        fontWeight: 600,
    },
    averagesDetail: {
        color: colors.text,
        fontSize: '13px',
        fontWeight: 700,
    },
    details: {
        borderTop: `1px solid rgba(148, 163, 184, 0.1)`,
        paddingTop: '10px',
    },
    summary: {
        color: colors.primary,
        fontSize: '12px',
        fontWeight: 600,
        cursor: 'pointer',
        listStyle: 'none',
        display: 'flex',
        alignItems: 'center',
        outline: 'none',
        userSelect: 'none' as const,
    },
    arrowIcon: {
        fontSize: '9px',
        width: '12px',
        display: 'inline-block',
    },
    detailsContent: {
        color: colors.textSecondary,
        fontSize: '11px',
        lineHeight: 1.5,
        marginTop: '8px',
        paddingLeft: '4px',
    },
    techRow: {
        display: 'flex',
        justifyContent: 'space-between',
        padding: '4px 0',
        borderBottom: '1px solid rgba(148, 163, 184, 0.05)',
        fontSize: '11px',
    },
    techLabel: {
        color: colors.textSecondary,
    },
    techVal: {
        color: colors.text,
        fontFamily: 'var(--font-mono, monospace)',
    },
    table: {
        width: '100%',
        borderCollapse: 'collapse' as const,
        marginTop: '8px',
        fontSize: '10px',
    },
    th: {
        textAlign: 'left' as const,
        color: colors.textSecondary,
        fontWeight: 600,
        padding: '6px 4px',
        borderBottom: '1px solid rgba(148, 163, 184, 0.1)',
    },
    tr: {
        borderBottom: '1px solid rgba(148, 163, 184, 0.05)',
    },
    td: {
        padding: '6px 4px',
        color: colors.text,
    },
    error: {
        color: colors.danger,
        fontSize: '12px',
        padding: '8px 0',
    },
    skeletonContainer: {
        display: 'flex',
        flexDirection: 'column' as const,
        gap: '16px',
        marginTop: '4px',
    },
    skeletonRow: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    skeletonScore: {
        width: '120px',
        height: '32px',
        backgroundColor: 'rgba(255, 255, 255, 0.06)',
        borderRadius: '4px',
    },
    skeletonDescription: {
        width: '180px',
        height: '14px',
        backgroundColor: 'rgba(255, 255, 255, 0.06)',
        borderRadius: '4px',
    },
    skeletonBadge: {
        width: '70px',
        height: '22px',
        backgroundColor: 'rgba(255, 255, 255, 0.06)',
        borderRadius: '4px',
    },
    skeletonTrack: {
        width: '100%',
        height: '14px',
        backgroundColor: 'rgba(255, 255, 255, 0.06)',
        borderRadius: '7px',
        margin: '8px 0',
    },
    skeletonText: {
        width: '80%',
        height: '14px',
        backgroundColor: 'rgba(255, 255, 255, 0.06)',
        borderRadius: '4px',
    },
    observatoryBest: {
        backgroundColor: colors.bgLight,
        borderRadius: '6px',
        padding: '12px',
        marginTop: '10px',
        display: 'flex',
        flexDirection: 'column' as const,
        gap: '4px',
    },
    observatoryBestTitle: {
        color: colors.textSecondary,
        fontSize: '10px',
        fontWeight: 700,
        letterSpacing: '0.04em',
    },
    observatoryBestDetail: {
        color: colors.textSecondary,
        fontSize: '11px',
        lineHeight: 1.4,
    },
    barRow: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: '12px',
        padding: '4px 0',
    },
    barLabel: {
        width: '140px',
        fontSize: '11px',
        color: colors.textSecondary,
        fontWeight: 500,
        whiteSpace: 'nowrap' as const,
        overflow: 'hidden' as const,
        textOverflow: 'ellipsis' as const,
    },
    barTrack: {
        flex: 1,
        height: '8px',
        backgroundColor: 'rgba(255, 255, 255, 0.08)',
        borderRadius: '4px',
        position: 'relative' as const,
    },
    barFill: {
        height: '100%',
        borderRadius: '4px',
    },
    barValue: {
        width: '30px',
        textAlign: 'right' as const,
        fontSize: '11px',
        fontFamily: 'var(--font-mono, monospace)',
        fontWeight: 700,
        color: colors.text,
    },
    clickableLink: {
        color: colors.primary,
        fontWeight: 700,
        fontSize: '13px',
        cursor: 'pointer',
        textDecoration: 'underline',
    },
    nonClickableText: {
        color: colors.text,
        fontWeight: 700,
        fontSize: '13px',
    },
} as const;
