"""Stable, deterministic Food identity.

Food previously had no intrinsic id at all (``get_entity_id()`` hardcoded
``None``); a fish "remembering" a specific food item had nothing reliable to
compare against between frames. This gives every Food a real id, generated by
a plain per-``Environment`` counter (mirrors
``PopulationTracker.generate_new_fish_id``), including on ``FoodPool`` reuse -
a pooled/reused object must get a fresh id, or it could be mistaken for
whatever food previously occupied that pool slot.
"""

from __future__ import annotations

import random

from core.entities.resources import Food, LiveFood
from core.environment import Environment
from core.object_pool import FoodPool


def _environment(seed: int = 0) -> Environment:
    return Environment(rng=random.Random(seed))


def test_food_get_entity_id_returns_its_real_id() -> None:
    env = _environment()
    food = Food(env, 10, 10, rng=random.Random(1))

    assert food.get_entity_id() is not None
    assert food.get_entity_id() == food.food_id


def test_food_ids_are_sequential_within_one_environment() -> None:
    env = _environment()
    food1 = Food(env, 10, 10, rng=random.Random(1))
    food2 = Food(env, 20, 20, rng=random.Random(2))
    food3 = Food(env, 30, 30, rng=random.Random(3))

    assert [food1.food_id, food2.food_id, food3.food_id] == [0, 1, 2]


def test_food_ids_reset_per_environment_not_process_global() -> None:
    """A fresh Environment (a fresh simulation) starts its own counter at 0 -
    ids are owned per-world, not a shared/global sequence."""
    env_a = _environment()
    env_b = _environment()

    food_a = Food(env_a, 0, 0, rng=random.Random(1))
    food_b = Food(env_b, 0, 0, rng=random.Random(1))

    assert food_a.food_id == food_b.food_id == 0


def test_explicit_food_id_is_respected() -> None:
    env = _environment()
    food = Food(env, 10, 10, rng=random.Random(1), food_id=42)

    assert food.food_id == 42
    # Explicit ids don't consume the environment's counter.
    next_food = Food(env, 20, 20, rng=random.Random(2))
    assert next_food.food_id == 0


def test_livefood_and_subclasses_get_real_ids_too() -> None:
    env = _environment()
    food = Food(env, 10, 10, rng=random.Random(1))
    live = LiveFood(env, 20, 20)

    assert food.food_id != live.food_id
    assert live.get_entity_id() == live.food_id


def test_food_pool_fresh_acquire_gets_a_real_id() -> None:
    env = _environment()
    pool = FoodPool(rng=random.Random(0))

    food = pool.acquire(env, 10, 10)

    assert food.get_entity_id() is not None


def test_food_pool_reuse_assigns_a_fresh_id() -> None:
    """A pooled object handed back out must be a logically NEW food item -
    reusing its old id could fool a fish still remembering the original."""
    env = _environment()
    pool = FoodPool(rng=random.Random(0))

    first = pool.acquire(env, 10, 10)
    first_id = first.food_id
    pool.release(first)

    second = pool.acquire(env, 50, 50)

    assert second is first  # the pool really did reuse the same Python object
    assert second.food_id != first_id


def test_food_ids_are_deterministic_across_separate_seeded_runs() -> None:
    """Two independent seed=42 simulations must assign identical food ids -
    a raw id(entity) fallback (the previous behavior) could never guarantee
    this, since it's a heap address that differs run to run."""
    from backend.simulation_runner import SimulationRunner

    def food_ids() -> list[int | None]:
        runner = SimulationRunner(seed=42)
        return sorted(e.get_entity_id() for e in runner.world.entities_list if isinstance(e, Food))

    ids_a = food_ids()
    ids_b = food_ids()

    assert ids_a == ids_b
    assert all(entity_id is not None for entity_id in ids_a)
    assert len(ids_a) > 0
